version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - nilnil
    - noctx
    - revive
    - staticcheck
    - unused
  settings:
    gocritic:
      disabled-checks:
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
          severity: warning
        - name: indent-error-flow
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
